services:
  openclaw-gateway:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      HOST: 127.0.0.1
      ALLOWED_ORIGINS: "*"
      # OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      # CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      # CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      # CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
      TAILSCALE_AUTH_KEY: ${TAILSCALE_AUTH_KEY}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace
      - tailscale-state:/var/lib/tailscale
      - tailscale-run:/var/run/tailscale
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    command: ["/start.sh"]

  openclaw-cli:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      # OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      BROWSER: echo
      # CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      # CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      # CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace
    env_file:
      - .env
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]

volumes:
  tailscale-state:
  tailscale-run:
